### PR TITLE
UI prototype

### LINKED ISSUE #14: Develop UI prototype
Create a prototype of the user interface (HTML, CSS, and JavaScript) using mock data that approximates real data that will be returned from the back-end.

### PR DESCRIPTION
**Pull request by eweitz**
Developed a basic prototype of the UI and Django templates for the "Upload and filter" and "Results" pages.  This resolves [Issue 14](https://github.com/DCGenomics/NCBI_August_Hackathon_Push_Button_Genomics_Solution/issues/14).

### CODE REVIEW

**Comment by ghost** [comment]
Eric - the URL you gave me that contains all the buttons that I need to work into the filtering program was

http://ec2-52-3-8-116.compute-1.amazonaws.com:8100/results/2e2e2e/

I believe. However, today I am receiving an ERR_CONNECTION_TIMED_OUT message.

Is there another way I could see these buttons? That way I can write the script appropriately.

Kindly,

Vincent A. Laufer, B.A.
NIH Medical Scientist Training Program (MD/PhD Program)
UAB | The University of Alabama at Birmingham
SHEL 121 | 1825 University Blvd | Birmingham, AL 35294-2128
P: 404.594.9834 | F: 205.975.8427 | vlaufer@uab.edu
www.mstp.uab.eduhttps://mail.ad.uab.edu/owa/redir.aspx?C=tIiysN_K30SBCjE8zqt9FWXCIMnhCdAIab0vbtyG1HBBFu7nmUjqDBViYVc9_Q9n6RqjxkpFG2U.&URL=http%3a%2f%2fwww.mstp.uab.edu%2f - Knowledge that will change the world

**Comment by seandavi** [comment]
I think all of the Hackathon machines have been deactivated, so that would
explain the timeout.

**Comment by eweitz** [comment]
@vlaufer, the instance is no longer accessible via that URL.  (@nyetsche had made it temporarily available from within the NIH network on Wednesday for the demo.)

Let's coordinate work for the VCF filtering feature in its GitHub issue -- https://github.com/DCGenomics/NCBI_August_Hackathon_Push_Button_Genomics_Solution/issues/8.  I'll copy over there some relevant comments I made last night in our Gitter chat room.

@seandavi, the AWS instance is still running (and will be until at tomorrow at 10 AM), but not accessible via HTTP.  We plan to create a public AMI and develop on that thereafter.

**Comment by ghost** [comment]
Got it - thanks Eric. I should be able to get on tonight and do some more work on:
1. vcf filtering
2. including liftover in the pipeline

**Pull request merged**
